name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main", "init"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata

      - name: Full-year calendar_HSCHOI
        uses: lowlighter/metrics@latest
        with:
          filename: output.metrics.plugin.isocalendar.fullyear.hschoi.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Full-year calendar_MATTHIEU
        uses: lowlighter/metrics@latest
        with:
          filename: output.metrics.plugin.isocalendar.fullyear.matthieu.svg
          token: ${{ secrets.METRICS_TOKEN_MATTHIEU }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Compact display in base plugin organization
        uses: lowlighter/metrics@latest
        with:
          filename: output.metrics.plugin.lines.history.organization.svg
          token: ${{ secrets.METRICS_TOKEN }}
#           organization: connectfit-team
          user: connectfit-team
          base: ""
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 20
          plugin_lines_history_limit: 10
          repositories_skipped: |
            lowlighter/metrics

      - name: Compact display in base plugin hschoi
        uses: lowlighter/metrics@latest
        with:
          filename: output.metrics.plugin.lines.history.hschoi.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: cnf-hschoi
          base: ""
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 20
          plugin_lines_history_limit: 10
          repositories_skipped: |
            lowlighter/metrics
              
      - name: Compact display in base plugin matthieu
        uses: lowlighter/metrics@latest
        with:
          filename: output.metrics.plugin.lines.history.matthieu.svg
          token: ${{ secrets.METRICS_TOKEN_MATTHIEU }}
          user: matthieugusmini
          base: ""
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 20
          plugin_lines_history_limit: 10
          repositories_skipped: |
            lowlighter/metrics

      - name: Full history calendar hschoi
        uses: lowlighter/metrics@latest
        with:
          filename: output.metrics.plugin.calendar.full.hschoi.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: cnf-hschoi
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

      - name: Full history calendar matthieu
        uses: lowlighter/metrics@latest
        with:
          filename: output.metrics.plugin.calendar.full.matthieu.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: matthieugusmini
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
          
      - name: Full history calendar swbae
        uses: lowlighter/metrics@latest
        with:
          filename: output.metrics.plugin.calendar.full.swbae.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: cnf-swbae
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

      - name: Full history calendar ludwig92
        uses: lowlighter/metrics@latest
        with:
          filename: output.metrics.plugin.calendar.full.ludwig92.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ludwig92
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
